# Generated by Django 5.0.6 on 2024-06-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_cus_code_customer_segment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
