# Generated by Django 5.0.6 on 2024-06-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_cus_code_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='segment_decription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
