# Generated by Django 5.0.6 on 2024-06-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_code_product_group_code_product_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
